### ISSUE TITLE
Error after deployment

### ISSUE THREAD

**Issue by rgalite** [wzin/opsworks_hipchat#2]
Hi,
Thanks for this cookbook, as I'm a huge fan of Hipchat, it is very useful to track my deployments.

I followed your tutorial, and here is the error I get after a deployment:

```
---- Begin output of /usr/bin/hipchat_notification.py *** *** myapp  ----
STDOUT: 
STDERR: Traceback (most recent call last):
File "/usr/bin/hipchat_notification.py", line 8, in <module>
user=sys.argv[4]
IndexError: list index out of range
---- End output of /usr/bin/hipchat_notification.py *** *** myapp  ----
```

I guess more args were supposed to be passed to the script?
I ssh'd to the instance and execute the script manually with an extra arg (the name of the instance) and it did work.

I think is not reading from the JSON provided. Any ideas?

**Comment by wzin** [comment]
Hi,
Are you using IAM users or the just the root account of your Amazon AWS Services?

**Comment by rgalite** [comment]
For the deployment?
I am using the deployer account registered on the instance.

**Comment by wzin** [comment]
I'm not sure if I understand you well but are you deploying the application from inside of the instance?

Please show me the output of:

opsworks-agent-cli get_json   | grep deplpoying_user

on the instance that you are deploying on.

**Comment by rgalite** [comment]
I am deploying from the opsworks console.

When it failed first, I ssh'd the instance to do it manually with the `deploy` user.

Sure. This is what I got:

```
"deploying_user": "arn:aws:iam::5xxxxxxxxxx7:root",
```

**Comment by wzin** [comment]
So you should be using IAM user to do that (as stated in the requirements in README). Root user is something that you probably not necessarily want to use in distributed environments.

Also: If you _do_ want to use root user, just remove the .split method from this line : https://github.com/wzin/opsworks_hipchat/blob/master/recipes/deploy.rb#L7 but you will  receive hipchat notification like "XXX deployed by arn:aws:iam::5xxxxxxxxxx7:root" instead of pretty "XXX deployed by Rudth" :)

root user has totally different format than IAM user, hence the problem :)

Let me know if it works for you!

**Comment by rgalite** [comment]
I think the offending line is here:
https://github.com/wzin/opsworks_hipchat/blob/b8c1b83a058bad35f3615a1d41342648223e5e18/recipes/deploy.rb#L7

```
    opsworks_user = deploy[:deploying_user].split('/')[1]
```

How did you end up with a deploying username containing a '/' ?

_Edit_: Didn't see your reply above.

**Comment by rgalite** [comment]
This is weird because in my Stack Settings, it says
- IAM role `arn:aws:iam::5xxxxxxxxxx7:role/aws-opsworks-service-role`
- Default IAM instance profile `arn:aws:iam::5xxxxxxxxxx7:instance-profile/aws-opsworks-ec2-role`

**Comment by rgalite** [comment]
Oh my bad. I just changed it at the layer level.
It was set to default. I'll try that and keep you posted.

**Comment by wzin** [comment]
IAM instance profile and IAM role is the definition of what your instance can and cannot do when it comes to requesting resources from other AWS services.

I am talking only about the user that is used for deployments - Typically you would log onto Opsworks console and click the "deploy" button. Then you would be using your personal IAM user which will perfectly work with my cookbook.

**Comment by rgalite** [comment]
Ahh thank you!
Yeah there was a mix-up here (and, more than that, I skipped the IAM users part from the README).
It's working now.
